### ISSUE TITLE
Sometimes it doesn't work

### ISSUE THREAD

**Issue by Gersonzao** [KwiiHours/EcosiaDark#6]
It simply doesn't make ecosia.org search pages dark and I need to reload the page, even though I waited a bit (maybe because the extension can be loading)

**Comment by KwiiHours** [comment]
I haven't run into this on my end yet -- what browser and version are you using?

**Comment by Gersonzao** [comment]
Brave | 1.42.68 Chromium: 103.0.5060.114 (Official Build) beta (64-bit)
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
Extension version: 1.52

**Comment by KwiiHours** [comment]
Thanks for the information!

I unfortunately haven't been able to recreate the issue on Brave (Current, Beta, or Nightly). How often does the darkmode not load, and do you have a way to reliably recreate this? Do you have any other extensions which may interact with your page styling?

Cheers

**Comment by Gersonzao** [comment]
> Thanks for the information!
> 
> I unfortunately haven't been able to recreate the issue on Brave (Current, Beta, or Nightly). How often does the darkmode not load, and do you have a way to reliably recreate this? Do you have any other extensions which may interact with your page styling?
> 
> Cheers

> Thanks for the information!
> 
> I unfortunately haven't been able to recreate the issue on Brave (Current, Beta, or Nightly). How often does the darkmode not load, and do you have a way to reliably recreate this? Do you have any other extensions which may interact with your page styling?
> 
> Cheers

It's very rare, (~1 in 250 pages opened). It only affects searches opened in new pages (it doesn't happen when I search something else in another Ecosia search page). Well, I don't know if any of these extensions change the page styling sometimes, but here's the list (only extensions that can access _ecosia.org_)

Adblock Plus - free ad blocker
Canvas Blocker - Fingerprint Protect
ClearURLs
Cookie AutoDelete
Decentraleyes
Ghostery – Privacy Ad Blocker
IDM Integration Module
Malwarebytes Browser Guard
Mate Translate – translator, dictionary
uBlock Origin development build
Vspeed Controller
Web Scrobbler

**Comment by Gersonzao** [comment]
By the way, I have already opened searches with the same browser instance (it wasn't when I just opened the browser and the extension was probably loading)

**Comment by KwiiHours** [comment]
I believe I may have found the issue, but I still haven't been able to recreate it personally. There should be an update available to you soon (1.54) in the [Chrome Webstore](https://chrome.google.com/webstore/detail/ecosia-darkmode/ncidpdcppimaiedanpmfgalibnfefpki). Please update to this version, and let me know if the issue continues. Hopefully this resolves it, and thanks for the help.

**Comment by KwiiHours** [comment]
This issue will be closed as update 1.54 should resolve it. If anyone still has this issue, please open a new thread.
